# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-26 03:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('data', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('form', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('data', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contacts', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
                ('data', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
                ('places', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
                ('status', models.SmallIntegerField(default=0)),
                ('risk', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('title', models.TextField(max_length=1024)),
                ('type', models.SmallIntegerField(default=0)),
                ('level', models.SmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=256)),
                ('policy', jsoneditor.fields.postgres_jsonfield.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Profile'),
        ),
    ]
