# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='infection',
            field=models.FloatField(default=1.0),
        ),
    ]
