# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-27 01:42
from __future__ import unicode_literals

from django.db import migrations
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_profile_infection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='data',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='form',
            name='form',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='places',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='risk',
            name='policy',
            field=django_postgres_extensions.models.fields.JSONField(default={}),
        ),
    ]
