# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-27 02:00
from __future__ import unicode_literals

from django.db import migrations
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200327_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='data',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='form',
            name='form',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='places',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='risk',
            name='policy',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(default={}),
        ),
    ]
