# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-31 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='need_isolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risk',
            name='isolation',
            field=models.BooleanField(default=False),
        ),
    ]
