# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_risk_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='need_test',
            field=models.BooleanField(default=False),
        ),
    ]
